import { LandingCardList } from '@/definition/commonInterface';

export const GetDummyBestList = () => {
  const dummyBestList: LandingCardList = {
    list: [
      {
        categoryId: 1,
        id: 1,
        questionDesc: '부동산 슬라이드 질문형 01',
        title: 'CardTitle',
        subTitle: 'CardSubTitle',
        videoUrl: '',
        color: '#fc0',
      },
      {
        categoryId: 1,
        id: 3,
        questionDesc: '부동산 슬라이드 질문형 03',
        title: 'CardTitle',
        subTitle: 'CardSubTitle',
        videoUrl: '',
        color: '#fc0',
      },
      {
        categoryId: 1,
        id: 4,
        questionDesc: '부동산 슬라이드 질문형 04',
        title: 'CardTitle',
        subTitle: 'CardSubTitle',
        videoUrl: '',
        color: '#fc0',
      },
      {
        categoryId: 1,
        id: 7,
        questionDesc: '부동산 슬라이드 질문형 07',
        title: 'CardTitle',
        subTitle: 'CardSubTitle',
        videoUrl: '',
        color: '#fc0',
      },
      {
        categoryId: 2,
        id: 10,
        questionDesc: '리테일&팝업 슬라이드 질문형 01',
        title: 'CardTitle',
        subTitle: 'CardSubTitle',
        videoUrl: '',
        color: '#f00',
      },
      {
        categoryId: 2,
        id: 14,
        questionDesc: '리테일&팝업 슬라이드 질문형 05',
        title: 'CardTitle',
        subTitle: 'CardSubTitle',
        videoUrl: '',
        color: '#f00',
      },
      {
        categoryId: 2,
        id: 16,
        questionDesc: '리테일&팝업 슬라이드 질문형 07',
        title: 'CardTitle',
        subTitle: 'CardSubTitle',
        videoUrl: '',
        color: '#f00',
      },
      {
        categoryId: 2,
        id: 18,
        questionDesc: '리테일&팝업 슬라이드 질문형 09',
        title: 'CardTitle',
        subTitle: 'CardSubTitle',
        videoUrl: '',
        color: '#f00',
      },
      {
        categoryId: 3,
        id: 20,
        questionDesc: '엔터프라이즈 슬라이드 질문형 02',
        title: 'CardTitle',
        subTitle: 'CardSubTitle',
        videoUrl: '',
        color: '#f0c',
      },
      {
        categoryId: 3,
        id: 23,
        questionDesc: '엔터프라이즈 슬라이드 질문형 05',
        title: 'CardTitle',
        subTitle: 'CardSubTitle',
        videoUrl: '',
        color: '#f0c',
      },
      {
        categoryId: 3,
        id: 24,
        questionDesc: '엔터프라이즈 슬라이드 질문형 06',
        title: 'CardTitle',
        subTitle: 'CardSubTitle',
        videoUrl: '',
        color: '#f0c',
      },
      {
        categoryId: 3,
        id: 25,
        questionDesc: '엔터프라이즈 슬라이드 질문형 07',
        title: 'CardTitle',
        subTitle: 'CardSubTitle',
        videoUrl: '',
        color: '#f0c',
      },
    ],
  };
  return dummyBestList;
};
