import { DetailParams, LandingCardList } from '@/definition/commonInterface';

export const GetDummyLabList = (params: DetailParams) => {
  const dummyLabList: LandingCardList = {
    list: [
      {
        categoryId: 1,
        id: 1,
        questionDesc: '부동산 슬라이드 질문형 01',
        title: 'Card Title',
        subTitle: 'Card Sub Title',
        videoUrl: '',
        color: '#fc0',
      },
      {
        categoryId: 1,
        id: 2,
        questionDesc: '부동산 슬라이드 질문형 02',
        title: 'Card Title',
        subTitle: 'Card Sub Title',
        videoUrl: '',
        color: '#fc0',
      },
      {
        categoryId: 1,
        id: 3,
        questionDesc: '부동산 슬라이드 질문형 03',
        title: 'Card Title',
        subTitle: 'Card Sub Title',
        videoUrl: '',
        color: '#fc0',
      },
      {
        categoryId: 1,
        id: 4,
        questionDesc: '부동산 슬라이드 질문형 04',
        title: 'Card Title',
        subTitle: 'Card Sub Title',
        videoUrl: '',
        color: '#fc0',
      },
      {
        categoryId: 1,
        id: 5,
        questionDesc: '부동산 슬라이드 질문형 05',
        title: 'Card Title',
        subTitle: 'Card Sub Title',
        videoUrl: '',
        color: '#fc0',
      },
      {
        categoryId: 1,
        id: 6,
        questionDesc: '부동산 슬라이드 질문형 06',
        title: 'Card Title',
        subTitle: 'Card Sub Title',
        videoUrl: '',
        color: '#fc0',
      },
      {
        categoryId: 1,
        id: 7,
        questionDesc: '부동산 슬라이드 질문형 07',
        title: 'Card Title',
        subTitle: 'Card Sub Title',
        videoUrl: '',
        color: '#fc0',
      },
      {
        categoryId: 1,
        id: 8,
        questionDesc: '부동산 슬라이드 질문형 08',
        title: 'Card Title',
        subTitle: 'Card Sub Title',
        videoUrl: '',
        color: '#fc0',
      },
      {
        categoryId: 1,
        id: 9,
        questionDesc: '부동산 슬라이드 질문형 09',
        title: 'Card Title',
        subTitle: 'Card Sub Title',
        videoUrl: '',
        color: '#fc0',
      },
      {
        categoryId: 2,
        id: 10,
        questionDesc: '리테일&팝업 슬라이드 질문형 01',
        title: 'Card Title',
        subTitle: 'Card Sub Title',
        videoUrl: '',
        color: '#f00',
      },
      {
        categoryId: 2,
        id: 11,
        questionDesc: '리테일&팝업 슬라이드 질문형 02',
        title: 'Card Title',
        subTitle: 'Card Sub Title',
        videoUrl: '',
        color: '#f00',
      },
      {
        categoryId: 2,
        id: 12,
        questionDesc: '리테일&팝업 슬라이드 질문형 03',
        title: 'Card Title',
        subTitle: 'Card Sub Title',
        videoUrl: '',
        color: '#f00',
      },
      {
        categoryId: 2,
        id: 13,
        questionDesc: '리테일&팝업 슬라이드 질문형 04',
        title: 'Card Title',
        subTitle: 'Card Sub Title',
        videoUrl: '',
        color: '#f00',
      },
      {
        categoryId: 2,
        id: 14,
        questionDesc: '리테일&팝업 슬라이드 질문형 05',
        title: 'Card Title',
        subTitle: 'Card Sub Title',
        videoUrl: '',
        color: '#f00',
      },
      {
        categoryId: 2,
        id: 15,
        questionDesc: '리테일&팝업 슬라이드 질문형 06',
        title: 'Card Title',
        subTitle: 'Card Sub Title',
        videoUrl: '',
        color: '#f00',
      },
      {
        categoryId: 2,
        id: 16,
        questionDesc: '리테일&팝업 슬라이드 질문형 07',
        title: 'Card Title',
        subTitle: 'Card Sub Title',
        videoUrl: '',
        color: '#f00',
      },
      {
        categoryId: 2,
        id: 17,
        questionDesc: '리테일&팝업 슬라이드 질문형 08',
        title: 'Card Title',
        subTitle: 'Card Sub Title',
        videoUrl: '',
        color: '#f00',
      },
      {
        categoryId: 2,
        id: 18,
        questionDesc: '리테일&팝업 슬라이드 질문형 09',
        title: 'Card Title',
        subTitle: 'Card Sub Title',
        videoUrl: '',
        color: '#f00',
      },
      {
        categoryId: 3,
        id: 19,
        questionDesc: '엔터프라이즈 슬라이드 질문형 01',
        title: 'Card Title',
        subTitle: 'Card Sub Title',
        videoUrl: '',
        color: '#f0c',
      },
      {
        categoryId: 3,
        id: 20,
        questionDesc: '엔터프라이즈 슬라이드 질문형 02',
        title: 'Card Title',
        subTitle: 'Card Sub Title',
        videoUrl: '',
        color: '#f0c',
      },
      {
        categoryId: 3,
        id: 21,
        questionDesc: '엔터프라이즈 슬라이드 질문형 03',
        title: 'Card Title',
        subTitle: 'Card Sub Title',
        videoUrl: '',
        color: '#f0c',
      },
      {
        categoryId: 3,
        id: 22,
        questionDesc: '엔터프라이즈 슬라이드 질문형 04',
        title: 'Card Title',
        subTitle: 'Card Sub Title',
        videoUrl: '',
        color: '#f0c',
      },
      {
        categoryId: 3,
        id: 23,
        questionDesc: '엔터프라이즈 슬라이드 질문형 05',
        title: 'Card Title',
        subTitle: 'Card Sub Title',
        videoUrl: '',
        color: '#f0c',
      },
      {
        categoryId: 3,
        id: 24,
        questionDesc: '엔터프라이즈 슬라이드 질문형 06',
        title: 'Card Title',
        subTitle: 'Card Sub Title',
        videoUrl: '',
        color: '#f0c',
      },
      {
        categoryId: 3,
        id: 25,
        questionDesc: '엔터프라이즈 슬라이드 질문형 07',
        title: 'Card Title',
        subTitle: 'Card Sub Title',
        videoUrl: '',
        color: '#f0c',
      },
    ],
  };

  if (params.categoryId == 0) {
    return dummyLabList.list;
  } else {
    const newData = dummyLabList.list.filter((item) => {
      return item.categoryId == params.categoryId;
    });
    return newData;
  }
};
